### ISSUE TITLE
Not working with laravel 7.X

### ISSUE THREAD

**Issue by hanakivan** [leinelissen/laravel-mix-react-css-modules#11]
When using this with laravel 7.X, you get the following error:

But it's just webpack's issue.
Here's a solution: https://stackoverflow.com/a/57903310/2880184

You dan really fix it yourself:
1. go to `node_modules/laravel-mix-react-css-modules`
2. find `localIdentName`
3. and replace the `var options` with `var options = { modules: { localIdentName: this$1.scopedName }, importLoaders: 1 };`

`Module build failed (from ./node_modules/css-loader/dist/cjs.js):
ValidationError: Invalid options object. CSS Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'localIdentName'. These properties are valid:
   object { url?, import?, modules?, sourceMap?, importLoaders?, localsConvention?, onlyLocals?, esModule? }
    at validate (/Users/ivan_1/projects/utm-tag-builder.com/www/node_modules/schema-utils/dist/validate.js:88:11)
    at Object.loader (/Users/ivan_1/projects/utm-tag-builder.com/www/node_modules/css-loader/dist/index.js:36:28)`

**Comment by leinelissen** [comment]
I'll release a new version that covers Laravel 7 shortly

**Comment by leinelissen** [comment]
By the way, this issue should only affect users who are on the Laravel Mix v6 Alpha, as v5 still uses an old version of css-loader. I will release a beta for this purpose shortly.

**Comment by leinelissen** [comment]
This problem should be fixed with the v3 that was just released to alpha for this package. It will be released as a regular version when Laravel Mix 6 hits the streets. Install using the following command: 
```
npm install laravel-mix-react-css-modules@next
```
