### ISSUE TITLE
SCSS Modules + Preact giving nesting warning

### ISSUE THREAD

**Issue by Brandoning** [leinelissen/laravel-mix-react-css-modules#6]
I'm trying to use this module to support scoped .scss imports in Preact which is built using Laravel Mix. I'm almost there, apart from PostCSS throwing a warning about nesting. The imported file has the .scss extension.

`Syntax Error: NonErrorEmittedError: (Emitted value instead of an instance of Error) CssSyntaxError: postcss-nested:`

It is strange because I can see this in the code which was intended to prevent this (I guess), but I think it's not merging in to Mix's Babel config properly.

```babelConfig() {
    return {
      plugins: [
        [
          "react-css-modules",
          {
            filetypes: {
              ".scss": {
                syntax: "postcss-scss",
                plugins: ["postcss-nested"]
              }
            },
            exclude: "node_modules",
            handleMissingStyleName: "warn",
            generateScopedName: this.scopedName,
            // THIS IS DIRTY HACK
            // Appearantly the context for laravel-mix lives in the node_modules folder
            // when calculating hashes for the ident names. This is pretty shitty behaviour,
            // but I am too lazy right now to fix it.
            context: path.resolve(__dirname + "/../../laravel-mix/src/builder")
          }
        ]
      ]
    };
  }
```

This is my mix config:

```
.preact([
     'resources/js/x/y.jsx'
     ], 'public/js/x.js')
   .reactCSSModules('[path]__[name]___[hash:base64]');
```

**Comment by leinelissen** [comment]
Could you mention the Laravel and Laravel Mix versions you are using, so I can take a look?

**Comment by Brandoning** [comment]
Mix: 4.1.4
Laravel: 5.8.32

Thanks 😄

**Comment by Brandoning** [comment]
I've just been doing a bit more testing and it seems to work, but not on imported components.

App.jsx imports a .scss file with nesting and it works fine, compiles with no errors and gives the randomly generated class names when I check.

App.jsx imports a component which imports a .scss file and it gives the nesting error.

**Comment by Brandoning** [comment]
It was actually a nested prop that was causing the issues, e.g.

```
font: {
size: 12px;
}
```

So it's https://github.com/jedmao/postcss-nested-props that i'll be needing.

**Comment by leinelissen** [comment]
> It was actually a nested prop that was causing the issues, e.g.
> 
> ```
> font: {
> size: 12px;
> }
> ```
> 
> So it's https://github.com/jedmao/postcss-nested-props that i'll be needing.

I didn't know this was a thing 😅. Props on figuring it out. Let me know if you need any further help.
