### ISSUE TITLE
options has an unknown property 'localIdentName'

### ISSUE THREAD

**Issue by webciter** [leinelissen/laravel-mix-react-css-modules#8]
Getting the following error

```
Module build failed (from ./node_modules/css-loader/dist/cjs.js):
ValidationError: Invalid options object. CSS Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'localIdentName'. These properties are valid:
   object { url?, import?, modules?, sourceMap?, importLoaders?, localsConvention?, onlyLocals?, esModule? 
```

**Comment by leinelissen** [comment]
Hi David!

Could you elaborate which version of Laravel, Laravel Mix and laravel-mix-react-css-modules you are using?

Cheers,
Lei

**Comment by webciter** [comment]
"laravel-mix-react-css-modules": "^2.0.0",
        "laravel-mix": "^5.0.1",

**Comment by webciter** [comment]
i believe its the css-loader.

**Comment by leinelissen** [comment]
Could you share your webpack.mix.js as well? I am trying to replicate your issue with a fresh Laravel instance, but it's working for me currently...

**Comment by leinelissen** [comment]
Could you also try doing a `rm -rf node_modules/ && npm install` to ensure that all correct versions are installed?

**Comment by leinelissen** [comment]
Okay, I've dug through the code and found a mismatching config with new versions of css-loader. I've created a new version that should fix the issue you're having. Could you do a `npm install laravel-mix-react-css-modules@beta` and see if that fixes the problem?

**Comment by webciter** [comment]
this works with version 3.4.2 of css-loader and the last version of laravel-mix-react-css-modules works with css-loader@2.0.1

**Comment by leinelissen** [comment]
> this works with version 3.4.2 of css-loader and the last version of laravel-mix-react-css-modules works with css-loader@2.0.1

You are right! However, that makes the error all the more weird, since the syntax then should have been correct already for Laravel Mix 5. Are you using a newer version of css-loader for some reason?
